FROM mysql:8.0

ENV TZ=Asia/Shanghai

COPY ../sql/init/01_init.sql /docker-entrypoint-initdb.d/01_init.sql

EXPOSE 3306

CMD ["mysqld", "--default-authentication-plugin=mysql_native_password", "--character-set-server=utf8mb4", "--collation-server=utf8mb4_unicode_ci"]
